<a href="https://colab.research.google.com/github/EfrainHernandezCortes/EDP2/blob/main/Tablero_de_colores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Probabilidades del tablero de colores.

Se importa la librería necesaria.

In [10]:
import numpy as np

Se define la matriz de transición que se obtuvo.

In [16]:
A = np.array([
    [1/4, 0, 1/4, 1/2],
    [1/2, 1/4, 0, 1/4],
    [1/4, 1/2, 1/4, 0],
    [0, 1/4, 1/2, 1/4],
], dtype=float)

Se define la función para obtener la potencia n de la matriz.

In [17]:
def potencia_matriz(A, n):
    P = np.eye(A.shape[0])
    for _ in range(n):
        P = A @ P
    return P


Tomaré n=1000, considerando un esto para cumplir la condición de haber pasado mucho tiempo.
Se imprime la matriz inicial elevada a la potencia n.

In [18]:
n = 1000
An = potencia_matriz(A, n)
print(np.round(An, 2))

[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]


Por lo tanto, se puede concluir que pasado mucho tiempo, todos los sectores son igual de probables.